MARKET1501:
  IMAGE_EXTENSIONS: [".jpg", ".jpeg", ".png"]
  DATAPATH: 'data/market1501'
  BB_TEST: 

CUHK03:
  IMAGE_EXTENSIONS: [".png"]
  DATAPATH: 'data/cuhk03'

MSMT17:
  IMAGE_EXTENSIONS: [".jpg", ".jpeg", ".png"]
  DATAPATH: 'data/msmt17'
VIPER:
  IMAGE_EXTENSIONS: [".jpg", ".jpeg", ".png"]
  DATAPATH: "data/viper"
LTCC:
  IMAGE_EXTENSIONS: [".jpg", ".jpeg", ".png"]
  DATAPATH: 'data/ltcc'
PRCC:
  IMAGE_EXTENSIONS: [".jpg"]
  DATAPATH: 'data/prcc'
VC_CLOTHES:
  IMAGE_EXTENSIONS: [".jpg"]
  DATAPATH: 'data/vcclothes'
REAL28:
  IMAGE_EXTENSIONS: [".jpeg"]
  DATAPATH: 'data/real28'

BATCH_SIZE: 32