PRETRAINED: "/Users/jurgendn/Documents/projects/personal/code/open-pose/storage/weights/body_pose_model_transfered.pth"
NO_RELU_LAYERS:
  [
    "conv5_5_CPM_L1",
    "conv5_5_CPM_L2",
    "Mconv7_stage2_L1",
    "Mconv7_stage2_L2",
    "Mconv7_stage3_L1",
    "Mconv7_stage3_L2",
    "Mconv7_stage4_L1",
    "Mconv7_stage4_L2",
    "Mconv7_stage5_L1",
    "Mconv7_stage5_L2",
    "Mconv7_stage6_L1",
    "Mconv7_stage6_L1",
  ]
STAGE_1:
  BLOCK_0:
    "conv1_1": [3, 64, 3, 1, 1]
    "conv1_2": [64, 64, 3, 1, 1]
    "pool1_stage1": [2, 2, 0]
    "conv2_1": [64, 128, 3, 1, 1]
    "conv2_2": [128, 128, 3, 1, 1]
    "pool2_stage1": [2, 2, 0]
    "conv3_1": [128, 256, 3, 1, 1]
    "conv3_2": [256, 256, 3, 1, 1]
    "conv3_3": [256, 256, 3, 1, 1]
    "conv3_4": [256, 256, 3, 1, 1]
    "pool3_stage1": [2, 2, 0]
    "conv4_1": [256, 512, 3, 1, 1]
    "conv4_2": [512, 512, 3, 1, 1]
    "conv4_3_CPM": [512, 256, 3, 1, 1]
    "conv4_4_CPM": [256, 128, 3, 1, 1]
  BLOCK_1:
    "conv5_1_CPM_L1": [128, 128, 3, 1, 1]
    "conv5_2_CPM_L1": [128, 128, 3, 1, 1]
    "conv5_3_CPM_L1": [128, 128, 3, 1, 1]
    "conv5_4_CPM_L1": [128, 512, 1, 1, 0]
    "conv5_5_CPM_L1": [512, 38, 1, 1, 0]
  BLOCK_2:
    "conv5_1_CPM_L2": [128, 128, 3, 1, 1]
    "conv5_2_CPM_L2": [128, 128, 3, 1, 1]
    "conv5_3_CPM_L2": [128, 128, 3, 1, 1]
    "conv5_4_CPM_L2": [128, 512, 1, 1, 0]
    "conv5_5_CPM_L2": [512, 19, 1, 1, 0]

STAGE_2:
  BLOCK_1:
    "Mconv1_stage2_L1": [185, 128, 7, 1, 3]
    "Mconv2_stage2_L1": [128, 128, 7, 1, 3]
    "Mconv3_stage2_L1": [128, 128, 7, 1, 3]
    "Mconv4_stage2_L1": [128, 128, 7, 1, 3]
    "Mconv5_stage2_L1": [128, 128, 7, 1, 3]
    "Mconv6_stage2_L1": [128, 128, 1, 1, 0]
    "Mconv7_stage2_L1": [128, 38, 1, 1, 0]
  BLOCK_2:
    "Mconv1_stage2_L2": [185, 128, 7, 1, 3]
    "Mconv2_stage2_L2": [128, 128, 7, 1, 3]
    "Mconv3_stage2_L2": [128, 128, 7, 1, 3]
    "Mconv4_stage2_L2": [128, 128, 7, 1, 3]
    "Mconv5_stage2_L2": [128, 128, 7, 1, 3]
    "Mconv6_stage2_L2": [128, 128, 1, 1, 0]
    "Mconv7_stage2_L2": [128, 19, 1, 1, 0]

LIMB_SEQ:
  [
    [2, 3],
    [2, 6],
    [3, 4],
    [4, 5],
    [6, 7],
    [7, 8],
    [2, 9],
    [9, 10],
    [10, 11],
    [2, 12],
    [12, 13],
    [13, 14],
    [2, 1],
    [1, 15],
    [15, 17],
    [1, 16],
    [16, 18],
    [3, 17],
    [6, 18],
  ]
MAP_INDEX:
  [
    [31, 32],
    [39, 40],
    [33, 34],
    [35, 36],
    [41, 42],
    [43, 44],
    [19, 20],
    [21, 22],
    [23, 24],
    [25, 26],
    [27, 28],
    [29, 30],
    [47, 48],
    [49, 50],
    [53, 54],
    [51, 52],
    [55, 56],
    [37, 38],
    [45, 46],
  ]
COLOR:
  [
    [255, 0, 0],
    [255, 85, 0],
    [255, 170, 0],
    [255, 255, 0],
    [170, 255, 0],
    [85, 255, 0],
    [0, 255, 0],
    [0, 255, 85],
    [0, 255, 170],
    [0, 255, 255],
    [0, 170, 255],
    [0, 85, 255],
    [0, 0, 255],
    [85, 0, 255],
    [170, 0, 255],
    [255, 0, 255],
    [255, 0, 170],
    [255, 0, 85],
  ]
SCALE_SEARCH: [0.5]
BOX_SIZE: 368
STRIDE: 8
PAD_VALUE: 128
THRESHOLD_1: 0.1
THRESHOLD_2: 0.05
