auto_resume: False

cudnn_benchmark: True
cudnn_deterministic: False
cudnn_enabled: True

data_dir: ""
gpus: [0, 1, 2, 3]
output_dir: "output"
log_dir: "log"
workers: "8x"
print_freq: 30

model:
  image_size: [192, 256]
  heatmap_size: [48, 64]
  init_weights: True
  name: pose_hrnet
  num_joints: 17
  pretrained: pretrained/model_hboe.pt
  sigma: 2
  tag_per_joint: True
  target_type: gaussian
  use_featuremap: True

  extra:
    stem_inplane: 64
    final_conv_kernel: 1
    pretrained_layers:
      [
        "conv1",
        "bn1",
        "conv2",
        "bn2",
        "layer1",
        "transition1",
        "stage2",
        "transition2",
        "stage3",
        "transition3",
        "stage4",
      ]

    stage2:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4]
      num_branches: 2
      num_channels: [32, 64]
      num_modules: 1

    stage3:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4, 4]
      num_branches: 3
      num_channels: [32, 64, 128]
      num_modules: 4

    stage4:
      block: BASIC
      fuse_method: SUM
      num_blocks: [4, 4, 4, 4]
      num_branches: 4
      num_channels: [32, 64, 128, 256]
      num_modules: 3

loss_use_different_joints_weight: False
loss_use_target_weight: True

debug_debug: True
debug_save_batch_images_gt: True
debug_save_batch_images_pred: True
debug_save_heatmaps_gt: True
debug_save_heatmaps_pred: True